spring.application.name=User
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/MiS1_User
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.config.import=optional:configserver:http://localhost:9999/configserver